// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWb4z8lQWzPzTpxmfCRJ0pladyH9lYeDU',
    appId: '1:528515022630:web:304e15f194d3d8efa4cbe7',
    messagingSenderId: '528515022630',
    projectId: 'nitnem-39118',
    authDomain: 'nitnem-39118.firebaseapp.com',
    storageBucket: 'nitnem-39118.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrY2zifJRQct83OaRCdgWx0KK2tgVChM',
    appId: '1:528515022630:android:def1aef53b7de945a4cbe7',
    messagingSenderId: '528515022630',
    projectId: 'nitnem-39118',
    storageBucket: 'nitnem-39118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc43ps9elnRkjHLbokHngRa2gjdPfxlFE',
    appId: '1:528515022630:ios:bf7479f7d09f4cbea4cbe7',
    messagingSenderId: '528515022630',
    projectId: 'nitnem-39118',
    storageBucket: 'nitnem-39118.firebasestorage.app',
    iosBundleId: 'com.example.nitnem',
  );
}
